version: '3.8'

services:
  php:
    build: ./backend/php
    container_name: m169-php
    volumes:
      - app-data:/var/www/html

  nginx:
    build: ./nginx
    container_name: m169-nginx
    ports:
      - "80:80"
    volumes:
      - app-data:/var/www/html
    depends_on:
      - php

volumes:
  app-data:
