version: '3.8'

services:
  php:
    image: ghcr.io/marzonev/m168-php:latest
    container_name: m169-php
    volumes:
      - ./backend:/var/www/html
    ports:
      - "80:80"  # Apache läuft auf Port 80
    depends_on:
      - db

  db:
    image: ghcr.io/marzonev/m169db:latest
    container_name: m169_postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

volumes:
  pgdata:
